//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uzor.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Uzor.Localization.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basics.
        /// </summary>
        public static string Basics {
            get {
                return ResourceManager.GetString("Basics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before Uzor.
        /// </summary>
        public static string BeforeStep {
            get {
                return ResourceManager.GetString("BeforeStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving as Image:.
        /// </summary>
        public static string BufferSavingLabel {
            get {
                return ResourceManager.GetString("BufferSavingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crop.
        /// </summary>
        public static string Crop {
            get {
                return ResourceManager.GetString("Crop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the item?.
        /// </summary>
        public static string DeleteQuestion {
            get {
                return ResourceManager.GetString("DeleteQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distances value:.
        /// </summary>
        public static string DistancesValue {
            get {
                return ResourceManager.GetString("DistancesValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to get out?.
        /// </summary>
        public static string ExitQuestion {
            get {
                return ResourceManager.GetString("ExitQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export projects in folder....
        /// </summary>
        public static string ExportProjects {
            get {
                return ResourceManager.GetString("ExportProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finishing.
        /// </summary>
        public static string Finishing {
            get {
                return ResourceManager.GetString("Finishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit first Uzor.
        /// </summary>
        public static string FirstUzorEdit {
            get {
                return ResourceManager.GetString("FirstUzorEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format:.
        /// </summary>
        public static string FormatLabel {
            get {
                return ResourceManager.GetString("FormatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import projects.
        /// </summary>
        public static string ImportProjects {
            get {
                return ResourceManager.GetString("ImportProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string LanguageLabel {
            get {
                return ResourceManager.GetString("LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long pattern - a full version of the form of the classic Belarusian pattern, consisting of three single.
        /// </summary>
        public static string LongUzorDescription {
            get {
                return ResourceManager.GetString("LongUzorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw two elements and go to manage your pattern-project.
        /// </summary>
        public static string LongUzorTip1 {
            get {
                return ResourceManager.GetString("LongUzorTip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All basic parameters are changed in the first tab.
        /// </summary>
        public static string LongUzorTip2 {
            get {
                return ResourceManager.GetString("LongUzorTip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Finnaly Uzor!.
        /// </summary>
        public static string MakeLongUzor {
            get {
                return ResourceManager.GetString("MakeLongUzor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Uzor.
        /// </summary>
        public static string MakeUzor {
            get {
                return ResourceManager.GetString("MakeUzor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mirror.
        /// </summary>
        public static string Mirror {
            get {
                return ResourceManager.GetString("Mirror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: .
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Uzor.
        /// </summary>
        public static string NewUzor {
            get {
                return ResourceManager.GetString("NewUzor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Uzor.
        /// </summary>
        public static string NextStep {
            get {
                return ResourceManager.GetString("NextStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not show again.
        /// </summary>
        public static string OffTips {
            get {
                return ResourceManager.GetString("OffTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opacity.
        /// </summary>
        public static string Opacity {
            get {
                return ResourceManager.GetString("Opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rendering optimization:.
        /// </summary>
        public static string OptimizationLabel {
            get {
                return ResourceManager.GetString("OptimizationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file access must be enabled!.
        /// </summary>
        public static string PermissionDenied {
            get {
                return ResourceManager.GetString("PermissionDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File saved in:.
        /// </summary>
        public static string SavedInLabel {
            get {
                return ResourceManager.GetString("SavedInLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        public static string SavedLabel {
            get {
                return ResourceManager.GetString("SavedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save current project color.
        /// </summary>
        public static string SaveProjectColor {
            get {
                return ResourceManager.GetString("SaveProjectColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving.
        /// </summary>
        public static string SavingLabelTip {
            get {
                return ResourceManager.GetString("SavingLabelTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving project:.
        /// </summary>
        public static string SavingProject {
            get {
                return ResourceManager.GetString("SavingProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit second Uzor.
        /// </summary>
        public static string SecondUzorEdit {
            get {
                return ResourceManager.GetString("SecondUzorEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Uzor:.
        /// </summary>
        public static string SelectItem {
            get {
                return ResourceManager.GetString("SelectItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set front color to all elements: .
        /// </summary>
        public static string SetFrontColorToAll {
            get {
                return ResourceManager.GetString("SetFrontColorToAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Side Uzor.
        /// </summary>
        public static string SideUzorEdit {
            get {
                return ResourceManager.GetString("SideUzorEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size:.
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сreating single pattern in a square format. Can be used for long patterns.
        /// </summary>
        public static string SquareUzorDescription {
            get {
                return ResourceManager.GetString("SquareUzorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rendering-mode is set to &quot;Low&quot;.
        /// </summary>
        public static string SwitchRenderingAlert {
            get {
                return ResourceManager.GetString("SwitchRenderingAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw some symmetrical dots in the center and start generation.
        /// </summary>
        public static string Tip1 {
            get {
                return ResourceManager.GetString("Tip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the mirror-tool for symmetrical drawing.
        /// </summary>
        public static string Tip2 {
            get {
                return ResourceManager.GetString("Tip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crop the finished field.
        /// </summary>
        public static string Tip3 {
            get {
                return ResourceManager.GetString("Tip3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can remove the crop by sliding the slider to the start position.
        /// </summary>
        public static string Tip3_2 {
            get {
                return ResourceManager.GetString("Tip3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can always save as a project, save an image and share it.
        /// </summary>
        public static string Tip4 {
            get {
                return ResourceManager.GetString("Tip4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .ubf and .lubf project-files are imported and exported in the settings.
        /// </summary>
        public static string Tip4_2 {
            get {
                return ResourceManager.GetString("Tip4_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (you can enable tips in the settings).
        /// </summary>
        public static string TipsEnableTip {
            get {
                return ResourceManager.GetString("TipsEnableTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show tips.
        /// </summary>
        public static string ViewTips {
            get {
                return ResourceManager.GetString("ViewTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
